const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const Device = require('../models/Device');
const User = require('../models/User');

// Export as CSV
router.get('/csv/:userId', async (req, res) => {
    try {
        const devices = await Device.find({ user: req.params.userId, isActive: true });
        
        let csv = "Name,Category,Wattage,Quantity,Hours per Day,Daily kWh (kWh),Monthly Cost (ETB)\n";
        
        let totalKwh = 0;
        for (let i = 0; i < devices.length; i++) {
            const d = devices[i];
            const kwh = (d.wattage * d.quantity * d.avgDailyHours / 1000).toFixed(2);
            totalKwh += parseFloat(kwh);
            csv += `"${d.name}",${d.category},${d.wattage},${d.quantity},${d.avgDailyHours},${kwh},${(kwh * 30 * 0.12).toFixed(2)}\n`;
        }
        
        // Add summary row
        csv += `\n"TOTAL",,,,,"${totalKwh.toFixed(2)}","${(totalKwh * 30 * 0.12).toFixed(2)}"\n`;
        
        res.setHeader('Content-Type', 'text/csv');
        res.setHeader('Content-Disposition', `attachment; filename=energy_report_${new Date().toISOString().split('T')[0]}.csv`);
        res.send(csv);
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
});

// Export as PDF
router.get('/pdf/:userId', async (req, res) => {
    try {
        const devices = await Device.find({ user: req.params.userId, isActive: true });
        const user = await User.findById(req.params.userId);
        
        let totalKwh = 0;
        for (let i = 0; i < devices.length; i++) {
            totalKwh += parseFloat(devices[i].dailyKwh);
        }
        
        const doc = new PDFDocument({ margin: 50 });
        
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=energy_report_${new Date().toISOString().split('T')[0]}.pdf`);
        doc.pipe(res);
        
        // Header
        doc.fontSize(25).text('Energy Consumption Report', { align: 'center' });
        doc.moveDown();
        
        // User Info
        doc.fontSize(12);
        doc.text(`Report Date: ${new Date().toLocaleString()}`);
        doc.text(`User Name: ${user ? user.name : 'N/A'}`);
        doc.text(`Email: ${user ? user.email : 'N/A'}`);
        doc.moveDown();
        
        // Summary Section
        doc.fontSize(16).text('Summary', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(12);
        doc.text(`📊 Total Daily Consumption: ${totalKwh.toFixed(2)} kWh`);
        doc.text(`💰 Estimated Monthly Cost: $${(totalKwh * 30 * 0.12).toFixed(2)}`);
        doc.text(`🌍 Carbon Footprint: ${(totalKwh * 0.233).toFixed(2)} kg CO2/day`);
        doc.moveDown();
        
        // Devices Table
        doc.fontSize(14).text('Devices List', { underline: true });
        doc.moveDown(0.5);
        
        let yPosition = doc.y;
        doc.fontSize(10);
        doc.text('Device Name', 50, yPosition);
        doc.text('Wattage', 200, yPosition);
        doc.text('Hours/Day', 280, yPosition);
        doc.text('Daily kWh', 360, yPosition);
        
        yPosition += 20;
        for (let i = 0; i < devices.length; i++) {
            const d = devices[i];
            const kwh = (d.wattage * d.quantity * d.avgDailyHours / 1000).toFixed(2);
            doc.text(d.name, 50, yPosition);
            doc.text(`${d.wattage}W`, 200, yPosition);
            doc.text(`${d.avgDailyHours} hrs`, 280, yPosition);
            doc.text(`${kwh} kWh`, 360, yPosition);
            yPosition += 20;
            
            if (yPosition > 700) {
                doc.addPage();
                yPosition = 50;
            }
        }
        
        // Footer
        doc.moveDown();
        doc.fontSize(10).text('Generated by Power Monitor System', { align: 'center' });
        
        doc.end();
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
});

// Get report summary (JSON)
router.get('/summary/:userId', async (req, res) => {
    try {
        const devices = await Device.find({ user: req.params.userId, isActive: true });
        const user = await User.findById(req.params.userId);
        
        let totalKwh = 0;
        const deviceDetails = [];
        
        for (let i = 0; i < devices.length; i++) {
            const d = devices[i];
            const kwh = (d.wattage * d.quantity * d.avgDailyHours / 1000).toFixed(2);
            totalKwh += parseFloat(kwh);
            deviceDetails.push({
                name: d.name,
                category: d.category,
                wattage: d.wattage,
                quantity: d.quantity,
                hoursPerDay: d.avgDailyHours,
                dailyKwh: kwh,
                monthlyCost: (kwh * 30 * 0.12).toFixed(2)
            });
        }
        
        res.json({
            success: true,
            report: {
                generatedAt: new Date(),
                user: { name: user?.name, email: user?.email },
                summary: {
                    totalDailyKwh: totalKwh.toFixed(2),
                    totalMonthlyKwh: (totalKwh * 30).toFixed(2),
                    totalMonthlyCost: `$${(totalKwh * 30 * 0.12).toFixed(2)}`,
                    carbonFootprint: `${(totalKwh * 0.233).toFixed(2)} kg CO2/day`
                },
                devices: deviceDetails
            }
        });
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
});

// Export as Excel (XLSX)
router.get('/excel/:userId', async (req, res) => {
    try {
        const devices = await Device.find({ user: req.params.userId, isActive: true });
        
        // Simple HTML table that Excel can read
        let html = `
            <html>
            <head>
                <meta charset="UTF-8">
                <title>Energy Report</title>
                <style>
                    th { background: #667eea; color: white; padding: 10px; }
                    td { padding: 8px; border-bottom: 1px solid #ddd; }
                    table { border-collapse: collapse; width: 100%; }
                </style>
            </head>
            <body>
                <h1>Energy Consumption Report</h1>
                <p>Generated: ${new Date().toLocaleString()}</p>
                <table border="1">
                    <thead>
                        <tr><th>Device Name</th><th>Category</th><th>Wattage (W)</th><th>Quantity</th><th>Hours/Day</th><th>Daily kWh</th><th>Monthly Cost (ETB)</th></tr>
                    </thead>
                    <tbody>
        `;
        
        let totalKwh = 0;
        for (let i = 0; i < devices.length; i++) {
            const d = devices[i];
            const kwh = (d.wattage * d.quantity * d.avgDailyHours / 1000).toFixed(2);
            totalKwh += parseFloat(kwh);
            html += `<tr><td>${d.name}</td><td>${d.category}</td><td>${d.wattage}</td><td>${d.quantity}</td><td>${d.avgDailyHours}</td><td>${kwh}</td><td>${(kwh * 30 * 0.12).toFixed(2)}</td></tr>`;
        }
        
        html += `
                    </tbody>
                    <tfoot>
                        <tr style="background:#f0f2f5"><td colspan="5"><strong>TOTAL</strong></td>
                        <td><strong>${totalKwh.toFixed(2)} kWh</strong></td>
                        <td><strong>${(totalKwh * 30 * 0.12).toFixed(2)} ETB</strong></td></tr>
                    </tfoot>
                </table>
                <p style="margin-top: 20px;">Generated by Power Monitor System</p>
            </body>
            </html>
        `;
        
        res.setHeader('Content-Type', 'application/vnd.ms-excel');
        res.setHeader('Content-Disposition', `attachment; filename=energy_report_${new Date().toISOString().split('T')[0]}.xls`);
        res.send(html);
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
});

module.exports = router;